repos:
  - repo: local
    hooks:
      - id: ruff_format
        name: ruff_format 
        entry: poetry run ruff format
        language: system
        types: [python]
        files: "^popsim/"
        exclude: "^popsim/tests/"
      - id: ruff_check
        name: ruff_check
        entry: poetry run ruff check --fix
        language: system
        types: [python]
        files: "^popsim/"
        exclude: "^popsim/tests/"