[project]
name = "xarray-jax"
version = "0.0.8"
description = ""
authors = [{name = "Allen Wang", email = "allenw@mit.edu"}]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jax>=0.7.0",
    "equinox>=0.13.0",
    "xarray>=2024.9.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "hypothesis>=6.112.1",
    "diffrax>=0.6.0",
    "pytest>=8.3.3",
    "pooch>=1.8.2",
    "ruff>=0.6.7",
    "pre-commit>=3.8.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
